# Generated by Django 2.0.6 on 2019-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachName', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('workDate', models.DateField()),
                ('entryDate', models.DateField()),
            ],
        ),
    ]
